name: Build Github Action
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run package
    - run: |
        mkdir -p ${HOME}/action_content
        cp action.yml ${HOME}/action_content/action.yml
        cp dist ${HOME}/action_content/
    - name: upload the action content
      uses: actions/upload-artifact@v1
      with:
        path: "${HOME}/action_content"
        name: "dist"

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*    
    - run: |
        git checkout -b ${GITHUB_REF##*/}-dist
        git rm -rf .
    - uses: actions/download-artifact@v1
      with:
        name: dist
        path: ${GITHUB_WORKSPACE}      