name: Branch Housekeeping
on:
  delete

jobs:
  clean:
    runs-on: ubuntu-latest
    if: endsWith(github.event.ref,'-dist') != true
    steps:
    - uses: actions/checkout@v2
    - name: configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
#    - uses: frabert/replace-string-action@v1.1
#      id: generate_branch_name
#      with:
#        pattern: 'refs/heads/(.*)'
#        string: "${{ github.event.ref }}"
#        replace-with: '$1-dist'
    - run: |
        git push origin --delete ${{ github.event.ref }}-dist
