name: Branch Housekeeping
on:
  delete

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - run: |
        git push origin --delete ${{github.event.ref}}-dist
