name: Build Github Action
on:
  delete

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - run: |
        git push origin --delete ${GITHUB_REF##*/}-dist
