name: Debug Workflow
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Read template from file
      id: packagejson
      uses: traversals-analytics-and-intelligence/file-reader-action@master
      with:
        file: ./package.json
    - id: packagejson_version
      uses: gr2m/get-json-paths-action@v1.x
      with:
        json: ${{ steps.packagejson.outputs.content }}
        version: "version"
    - run: "echo bar is ${{ steps.packagejson_version.outputs.version }}"
