name: Debug Workflow
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Read template from file
      id: template
      uses: traversals-analytics-and-intelligence/file-reader-action@master
      with:
        file: ./package.json
    - name: Get the template output
      run: echo "${{ steps.template.outputs.content }}"
    - id: data
      uses: gr2m/get-json-paths-action@v1.x
      with:
        json: ${{ steps.template.outputs.content }}
        bar: "version"
    - run: "echo bar is ${{ steps.data.outputs.bar }}"
