name: Debug Workflow
on:
  issues:
    types:
      - labeled
      - unlabeled

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create changelog
      uses: nolte/github-action/utils/changeLog@feature/shasum
      with:
        CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CHANGELOG_GITHUB_PROJECT: "gh-action-workflow-test"
        CHANGELOG_GITHUB_SINCE_TAG: "v0.21.0"
        CHANGELOG_GITHUB_USER: "nolte"

    - name: Read Pre Release Version from File
      id: pre_release_version
      uses: traversals-analytics-and-intelligence/file-reader-action@master
      with:
        file: /github/workspace/CHANGELOG.md
    - run: |
        echo "${{ steps.pre_release_version.outputs.content }}"
