name: Finish Release
on:
  pull_request:
    types: [closed]
    branches:
      - "master"

jobs:
  updatenextdev:
    name: Prepare Next Develop Version
    runs-on: ubuntu-latest
    steps:

    - name: configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - uses: actions/checkout@v2
      with:
        ref: develop
    # https://github.com/actions/checkout#Fetch-all-branches
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

    - run: |
        git rebase master

    - name: Read Pre Release Version from File
      id: pre_release_version
      uses: traversals-analytics-and-intelligence/file-reader-action@master
      with:
        file: ./version.txt

    - uses: actions/setup-python@v1
    - name: set PY
      run: echo "::set-env name=PY::$(python --version --version | sha256sum | cut -d' ' -f1)"

    - name: set next dev version
      uses: nolte/github-action/utils/bump2version@feature/shasum
      with:
        currentVersion: "${{ steps.pre_release_version.outputs.content }}"
        part: minor

    - name: Read Dev Version from File
      id: release_version
      uses: traversals-analytics-and-intelligence/file-reader-action@master
      with:
        file: ./version.txt

    - name: Commit files
      run: |
        git commit -m "Update to the next Dev Version ${{ steps.release_version.outputs.content }}" -a
        git push --all origin
